# Generated by `cargo xtask formula` in michel-onstein/acs for each release
# (scripts/update-tap.sh): edit the generator there, not this file.
class Acs < Formula
  desc "Persistent, reconnecting remote shells over ssh"
  homepage "https://github.com/michel-onstein/acs"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/michel-onstein/acs/releases/download/v0.10.3/acs-0.10.3-aarch64-apple-darwin.tar.gz"
      sha256 "f7b3b5853e2f9a3d1ce93d046e9cfbc3dccf2d1006782c079b11037be56b6e16"
    end

    on_intel do
      url "https://github.com/michel-onstein/acs/releases/download/v0.10.3/acs-0.10.3-x86_64-apple-darwin.tar.gz"
      sha256 "d64245f72540cb4878b4ebe305bc8abc70d0a4850a29cfe312529ad380edfe68"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/michel-onstein/acs/releases/download/v0.10.3/acs-0.10.3-aarch64-unknown-linux-musl.tar.gz"
      sha256 "9e96bc1b905b164db0537e57cf598a9d0cf7dee68c6ec801b27995081155ded1"
    end

    on_intel do
      url "https://github.com/michel-onstein/acs/releases/download/v0.10.3/acs-0.10.3-x86_64-unknown-linux-musl.tar.gz"
      sha256 "2b917bb037123132c13e0f552de6c2ba1a2d538d8150551190468feeeabaf605"
    end
  end

  def install
    bin.install "acs"
  end

  test do
    out = shell_output("#{bin}/acs --version")
    assert_match "acs #{version} ", out
    remotes = out[/^installs remotes: (.*)$/, 1].to_s.split(", ")
    assert_includes remotes, "x86_64-unknown-linux-musl"
    assert_includes remotes, "aarch64-unknown-linux-musl"
  end
end
