# Generated by `cargo xtask formula` in michel-onstein/acs for each release
# (scripts/update-tap.sh): edit the generator there, not this file.
#
# acs releases are signed; SHA256SUMS.sig is checked against this key:
#   ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILbxQW5C9X7CdwcQ4bab0gsQi4Evk2xfgmI/972dlHCb acs release signing
# Verify a release by hand:
#   printf 'releases@acs namespaces="acs-release" %s\n' "$key" > allowed
#   ssh-keygen -Y verify -f allowed -I releases@acs -n acs-release -s SHA256SUMS.sig < SHA256SUMS
class Acs < Formula
  desc "Persistent, reconnecting remote shells over ssh"
  homepage "https://github.com/michel-onstein/acs"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/michel-onstein/acs/releases/download/v0.12.1/acs-0.12.1-aarch64-apple-darwin.tar.gz"
      sha256 "93e43f8ae7a1aa13453d911a7ad7b729ea3096d6d0c4c5416513c741397bd549"
    end

    on_intel do
      url "https://github.com/michel-onstein/acs/releases/download/v0.12.1/acs-0.12.1-x86_64-apple-darwin.tar.gz"
      sha256 "ef7672c52a55f2aab4f3f31e851ec95c7e29ccb70ce1d97d013ff06aed2861c7"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/michel-onstein/acs/releases/download/v0.12.1/acs-0.12.1-aarch64-unknown-linux-musl.tar.gz"
      sha256 "7d3ad775163f821d0914d6c80d17864b768bd02b33328d9644a84a0c6050b8fc"
    end

    on_intel do
      url "https://github.com/michel-onstein/acs/releases/download/v0.12.1/acs-0.12.1-x86_64-unknown-linux-musl.tar.gz"
      sha256 "347929a4c11f41577f7c59726ffaa58fab50207a3872693be7b1578ec7135c0d"
    end
  end

  def install
    bin.install "acs"
  end

  test do
    out = shell_output("#{bin}/acs --version")
    assert_match "acs #{version} ", out
    remotes = out[/^installs remotes: (.*)$/, 1].to_s.split(", ")
    assert_includes remotes, "x86_64-unknown-linux-musl"
    assert_includes remotes, "aarch64-unknown-linux-musl"
  end
end
