# Generated by `cargo xtask formula` in michel-onstein/acs for each release
# (scripts/update-tap.sh): edit the generator there, not this file.
class Acs < Formula
  desc "Persistent, reconnecting remote shells over ssh"
  homepage "https://github.com/michel-onstein/acs"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/michel-onstein/acs/releases/download/v0.6.0/acs-0.6.0-aarch64-apple-darwin.tar.gz"
      sha256 "3965c3440a9360d8f68f8e82f0d9b59456ae0361cd707c914125511772096dc4"
    end

    on_intel do
      url "https://github.com/michel-onstein/acs/releases/download/v0.6.0/acs-0.6.0-x86_64-apple-darwin.tar.gz"
      sha256 "9ddf8b68f02c1e3cf62763b94bcef53f7129dff47667db978e06143634108639"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/michel-onstein/acs/releases/download/v0.6.0/acs-0.6.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "e2bd732cbe3a868d00c470953edc70bfe185f370b3ef6749663554a67a064bb2"
    end

    on_intel do
      url "https://github.com/michel-onstein/acs/releases/download/v0.6.0/acs-0.6.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "848ded37c773d0076954a26ab9601692f0f60872b60a0ba091977982f56e7812"
    end
  end

  def install
    bin.install "acs"
  end

  test do
    out = shell_output("#{bin}/acs --version")
    assert_match "acs #{version} ", out
    remotes = out[/^installs remotes: (.*)$/, 1].to_s.split(", ")
    assert_includes remotes, "x86_64-unknown-linux-musl"
    assert_includes remotes, "aarch64-unknown-linux-musl"
  end
end
